# Generated by Django 2.2.7 on 2022-01-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0002_auto_20220127_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vunerability',
            options={'verbose_name': 'Vulnerabilidade', 'verbose_name_plural': 'Vulnerabilidade'},
        ),
    ]
