# Generated by Django 2.2.7 on 2022-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0003_auto_20220127_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='vunerability',
            name='status',
            field=models.IntegerField(choices=[(1, 'Corrigido'), (2, 'Não Corrigido')], default=2),
        ),
    ]
