# Generated by Django 2.2.7 on 2022-01-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0004_vunerability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vunerability',
            name='vulnerability_severity',
            field=models.IntegerField(blank=True, choices=[(3, 'Baixa'), (4, 'Médio'), (5, 'Alta'), (6, 'Crítico')], null=True, verbose_name='Severity'),
        ),
    ]
